### ISSUE TITLE
Run ZooKeeper under supervision of Exhibitor

### ISSUE THREAD

**Issue by CyberDem0n** [zalando/saiki-kewan#3]
Hi there.
If you have time may be you would be interested to have a look on Exhibitor appliance: https://github.com/zalando/exhibitor-appliance

It does basically the same as your appliance - creates ZooKeeper cluster. But it does it really smart - it allows to manage ZooKeeper cluster as a whole (adding new nodes, removing dead nodes, performing rolling restarts of cluster nodes and so on). And as a huge bonus, it does everything automatically. Plus it has rest-api interface. This interface is mostly useful to get list of all cluster nodes.

**Comment by chutium** [comment]
Hi Alex, thanks for the information, we are also planning to use exhibitor to supervise the zookeeper cluster, currently the master branch of saiki-kewan is aimed at creating a minimal set of STUPS-specified zookeeper appliance.

and we thought a zookeeper cluster with exhibitor could be created as a separate branch, now for sure we will try out your appliance, and maybe we can contribute together in this appliance that you created. this should also be a STUPS appliance right? looked shortly at your Dockerfile, shouldn't be creating from zalando-jdk image? (instead of ```FROM ubuntu:14.04``` and ```apt-get install $BUILD_DEPS``` to install jdk in Dockerfile...)

**Comment by CyberDem0n** [comment]
As I understand there is no big difference between standalone and WAR. For me standalone was just easy to run. Exhibitor-core for me also doesn't really make sense, because we are building kind of micro-services and if some other services demand ZooKeeper they could just use existing cluster.

Yes, exhibitor appliance could be deployed by stups-senza, and actually is already deployed. You also could try it. Docker image is available under acid/exhibitor:0.1-SNAPSHOT

And about Dockerfile - I don't see any problem with ```FROM ubuntu:14.04```. We are not forced to use zalando images. Actually there are two approaches: either we are building Exhibitor locally and copying exhibitor.jar  info docker image or just build everything inside docker. I've chosen the second one, build takes more time, but it should work for everybody without having anything but docker.

**Comment by chutium** [comment]
Hi, sure standalone mode is most directly way to run, use it as WAR should be different, IMHO we can use Exhibitor WAR within Tomcat or whatever, standalone mode Exhibitor will be running as a web server.

on each node we use an Exhibitor process to supervise zookeeper process, but if Exhibitor process crashed, the supervisior is gone. so Exhibitor become to a dangerous point again in the whole system, i think maybe Tomcat with Exhibitor WAR will be a little bit stable than running Exhibitor as a web server right?

And maybe for compliance or monitoring purpose we can use Exhibitor with Zomcat... who knows, only an option : )

To docker image, of course we are not forced to use zalando images, if there is no problem with zalando certificates or auditing requirement or something else, certainly we do not need to use zalando images...

I will try to use acid/exhibitor:0.1-SNAPSHOT today, will give feedback later, thanks again for this exciting tool box.

**Comment by chutium** [comment]
@CyberDem0n i made some small bugfix: https://github.com/zalando/exhibitor-appliance/pull/1

i will close this issue and we can continue to discuss with each other in exhibitor-appliance project.

Thanks.
