### ISSUE TITLE
Permission denied: '/opt/zookeeper-3.4.6/conf/zoo.cfg'

### ISSUE THREAD

**Issue by ehartung** [zalando/saiki-kewan#6]
The Zookeeper configuration is not writeable by the Python script, i.e. additional Zookeeper nodes cannot be added:
```
PermissionError: [Errno 13] Permission denied: '/opt/zookeeper-3.4.6/conf/zoo.cfg'
```

**Comment by chutium** [comment]
maybe there is some issue by the new python docker template, at the moment you can try the use our released kewan image:
pierone.stups.zalan.do/saiki/kewan:1.0

we will try to fix the permission problem now.

**Comment by ehartung** [comment]
I fixed it locally and can create a pull-request if you like.

**Comment by chutium** [comment]
sure, thanks a lot
